import * as React from 'react';
import Head from 'next/head';
import Header from '../../common/header';
import Footer from '../../common/footer';
import Sidebar from '../../common/sidebar';

import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import Button from '@mui/material/Button';
import Link from '@mui/material/Link';

import styles from '@/styles/Home.module.css';

import { Work_Sans } from 'next/font/google';
const workSans = Work_Sans({ subsets: ['latin'] });

import { createTheme, ThemeProvider } from '@mui/material';
export default function addresses () {
    const theme = createTheme({
        typography: {
            fontFamily: [
            'Work Sans',            
            ].join(','),
        },
    });      


return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <ThemeProvider theme={theme}>
        <main className={styles.main}>
           <Header/>
                <div className={styles.paddingTB60}>                
                    <Container className={styles.containerBox}>
                        <Grid container spacing={3}>
                            <Grid item md={3} xs={12} className={styles.sidebarGrid}>
                                <Sidebar/>
                            </Grid>

                            <Grid item md={9} xs={12}>
                                <div className={styles.wrapTitle}>
                                    <Typography variant="h4" >
                                        Addresses
                                    </Typography>
                                </div>     

                                <div className={`${styles["wrapBox"]} ${styles["addressSection"]}`}> 

                                    <div className={styles.boxInfo}>
                                        <div className={styles.wrapSubTitle}>
                                            <Typography variant="h4" >
                                                Default address
                                            </Typography> 
                                        </div> 

                                        <div className={styles.boxInfoBody}>                                        
                                            <List>
                                                <ListItem>
                                                    <div className={styles.addresses}>
                                                        <div className={styles.addressesType}>
                                                            <Typography variant="h4">
                                                                Home
                                                            </Typography>
                                                            {/* <Typography variant="h6" >
                                                                <Link href='#'> Set as default </Link>
                                                            </Typography> */}
                                                        </div>

                                                        <Typography variant="h5">
                                                            Keanu Reeves

                                                        </Typography>

                                                        <Typography variant="body1">
                                                            keanureeves@gmail.com
                                                        </Typography>

                                                        <Typography variant="body1">
                                                            3rd floor, CBA technologies 57XF+XM <br/> 
                                                            Dubai Dubai UAE    
                                                        </Typography>

                                                        <Typography variant="body1">
                                                            +971-58-1234659
                                                        </Typography>

                                                        <div className={styles.actionBtn}>
                                                            <Button variant="outlined" 
                                                            className={`${styles["btn"]} ${styles["btn_outlined"]}`}> Edit </Button>
                                                            <Button variant="text" className={`${styles["btn"]} ${styles["btn_delete"]}`}>Delete</Button>                                            
                                                        </div>

                                                    </div>
                                                </ListItem>
                                            
                                            </List>                                       
                                        </div>
                                    </div> 



                                    <div className={styles.boxInfo}>
                                        <div className={styles.wrapSubTitle}>
                                            <Typography variant="h4" >
                                                Other addresses
                                            </Typography> 
                                        </div> 

                                        <div className={styles.boxInfoBody}>                                        
                                            <List>
                                                <ListItem>
                                                    <div className={styles.addresses}>
                                                        <div className={styles.addressesType}>
                                                            <Typography variant="h4">
                                                                Home
                                                            </Typography>
                                                            <Typography variant="h6" >
                                                                <Link href='#'> Set as default </Link>
                                                            </Typography>
                                                        </div>

                                                        <Typography variant="h5">
                                                            Keanu Reeves

                                                        </Typography>

                                                        <Typography variant="body1">
                                                            keanureeves@gmail.com
                                                        </Typography>

                                                        <Typography variant="body1">
                                                            3rd floor, CBA technologies 57XF+XM <br/> 
                                                            Dubai Dubai UAE    
                                                        </Typography>

                                                        <Typography variant="body1">
                                                            +971-58-1234659
                                                        </Typography>

                                                        <div className={styles.actionBtn}>
                                                            <Button variant="outlined" 
                                                            className={`${styles["btn"]} ${styles["btn_outlined"]}`}> Edit </Button>
                                                            <Button variant="text" className={`${styles["btn"]} ${styles["btn_delete"]}`}>Delete</Button>                                            
                                                        </div>

                                                    </div>
                                                </ListItem>

                                                <ListItem>
                                                    <div className={styles.addresses}>
                                                        <div className={styles.addressesType}>
                                                            <Typography variant="h4">
                                                                Home
                                                            </Typography>
                                                            <Typography variant="h6" >
                                                                <Link href='#'> Set as default </Link>
                                                            </Typography>
                                                        </div>

                                                        <Typography variant="h5">
                                                            Keanu Reeves

                                                        </Typography>

                                                        <Typography variant="body1">
                                                            keanureeves@gmail.com
                                                        </Typography>

                                                        <Typography variant="body1">
                                                            3rd floor, CBA technologies 57XF+XM <br/> 
                                                            Dubai Dubai UAE    
                                                        </Typography>

                                                        <Typography variant="body1">
                                                            +971-58-1234659
                                                        </Typography>

                                                        <div className={styles.actionBtn}>
                                                            <Button variant="outlined" 
                                                            className={`${styles["btn"]} ${styles["btn_outlined"]}`}> Edit </Button>
                                                            <Button variant="text" className={`${styles["btn"]} ${styles["btn_delete"]}`}>Delete</Button>                                            
                                                        </div>

                                                    </div>
                                                </ListItem>

                                                <ListItem>
                                                    <div className={styles.addresses}>
                                                        <div className={styles.addressesType}>
                                                            <Typography variant="h4">
                                                                Home
                                                            </Typography>
                                                            <Typography variant="h6" >
                                                                <Link href='#'> Set as default </Link>
                                                            </Typography>
                                                        </div>

                                                        <Typography variant="h5">
                                                            Keanu Reeves

                                                        </Typography>

                                                        <Typography variant="body1">
                                                            keanureeves@gmail.com
                                                        </Typography>

                                                        <Typography variant="body1">
                                                            3rd floor, CBA technologies 57XF+XM <br/> 
                                                            Dubai Dubai UAE    
                                                        </Typography>

                                                        <Typography variant="body1">
                                                            +971-58-1234659
                                                        </Typography>

                                                        <div className={styles.actionBtn}>
                                                            <Button variant="outlined" 
                                                            className={`${styles["btn"]} ${styles["btn_outlined"]}`}> Edit </Button>
                                                            <Button variant="text" className={`${styles["btn"]} ${styles["btn_delete"]}`}>Delete</Button>                                            
                                                        </div>

                                                    </div>
                                                </ListItem>

                                               
                                            </List>                                       
                                        </div>
                                    </div> 

                                </div>            
                            </Grid> 
                        </Grid>
                    </Container>

                </div>

          

            
            <Footer/>
        </main>
    </ThemeProvider>
    </>
  )
}
