import * as React from 'react';
import Head from 'next/head';
import Header from '../../common/header';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Input from '@mui/material/Input';
import Email from '../img/emailIcon.svg';
import styles from '@/styles/Home.module.css';

import { Work_Sans } from 'next/font/google';
const workSans = Work_Sans({ subsets: ['latin'] });

import { createTheme, ThemeProvider } from '@mui/material';
export default function login () {
    const theme = createTheme({
        typography: {
            fontFamily: [
            'Work Sans',            
            ].join(','),
        },
    });   

return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <ThemeProvider theme={theme}>
        <main className={`${styles["main"]} ${styles["loginBG"]}`}>
            <Header/>
            <div className={styles.loginBoxCenter}>                
                <Container className={styles.containerBox}>
                    <Grid container justifyContent="center" spacing={3}>                           
                        <Grid item md={5} sm={8} xs={12}>
                            <div className={styles.loginBox}>                                
                                <Typography variant="h2">
                                    Forgot your Password?
                                </Typography>

                                <Typography variant="body1">
                                    Please provide your account's email, and we'll send password reset link to that address.
                                </Typography>
                                
                            
                                <div className={styles.formControl}>    
                                    <label className={styles.formLabel}> Email </label>     
                                    <Email className={styles.formIcon} />                                            
                                    <Input  className={styles.formInput} placeholder="Email" />
                                </div>

                                <div className={styles.inline}>
                                <Button variant="outlined" href="signIn" className={`${styles["btn"]} ${styles["btn_secondary"]}`} > Back to sign in </Button>
                                <Button variant="contained" className={`${styles["btn"]} ${styles["btn_primary"]}`} > Reset Password </Button>                                    
                                
                                </div>
                            </div> 
                        </Grid> 
                    </Grid>
                </Container>
            </div>
        </main>
    </ThemeProvider>
    </>
  )
}
