import * as React from 'react';
import Head from 'next/head';
import Header from '../pages/common/header';
import Footer from '../pages/common/footer';

import styles from '@/styles/Home.module.css';

import { Work_Sans } from 'next/font/google';
const workSans = Work_Sans({ subsets: ['latin'] })



import { createTheme, ThemeProvider } from '@mui/material';



export default function Home() {
    const theme = createTheme({
        typography: {
          fontFamily: [
            'Work Sans',            
          ].join(','),
        },});

  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <ThemeProvider theme={theme}>
        <main className={styles.main}>
           <Header/>

            <Footer/>
        </main>
    </ThemeProvider>
    </>
  )
}
